spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_db
    password: postgres
    username: postgres
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yml
    enabled: true
    drop-first: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /docs/openapi.yaml
app:
  jwt:
    secret: "someSecretKey"
    tokenExpiration: 50m
    refreshTokenExpiration: 100m
server:
  port: 8080